import {
  AudioLines,
  Bot,
  BriefcaseBusiness,
  Code2,
  FileText,
  Globe2,
  GraduationCap,
  ImageIcon,
  Languages,
  LayoutGrid,
  Map,
  MessageSquare,
  Mic2,
  PackageOpen,
  Palette,
  PenLine,
  Search,
  Sparkles,
  Users,
  Video,
  WandSparkles,
  type LucideIcon,
} from "lucide-react";

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "AI 聊天对话": MessageSquare,
  "AI 智能体": Bot,
  "AI 绘图": Palette,
  "AI 图像处理": ImageIcon,
  "AI 视频生成": Video,
  "AI 数字人": Users,
  "AI 语音生成": AudioLines,
  "AI 角色生成": WandSparkles,
  "AI 提示词": Sparkles,
  "AI 搜索引擎": Search,
  "AI 行业工具": BriefcaseBusiness,
  "AI 写作助手": PenLine,
  "AI 文档办公": FileText,
  "AI 学习资源": GraduationCap,
  "AI 思维导图": Map,
  "AI 翻译工具": Languages,
  "AI 编程开发": Code2,
  "AI 网站生成": LayoutGrid,
  "AI 电商工具": PackageOpen,
  "AI 会议助手": Mic2,
  "AI 综合工具": LayoutGrid,
  国产大模型: Globe2,
  "AI 开源工具": Code2,
  "AI 国外工具": Globe2,
  未分类: LayoutGrid,
};

export function getCategoryIcon(name: string): LucideIcon {
  return CATEGORY_ICONS[name] ?? LayoutGrid;
}
